
try {
  ......
  throw ("my exception");
  throw new Error("my error");
  .....
}
catch (exception) {
  ......
}
finally {
  ......
}